language: python
os:
  - "osx"
python:
  - "2.7"
  - "3.5"
install: 
  - "pip install coverage"
  - "pip install periodictable"
  - "pip install codecov"
  - "pip install scipy"
  - "python setup.py install"
script: 
  - "nosetests --with-coverage --cover-package=phreeqpython"
after_success:
  - "codecov"
